name: Sync dist folder to dsg-web repo

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:

  # Trigger on push to the main branch if the dist folder is updated
  push:
    branches:
      - master
    paths:
      - 'dist/**'

jobs:
  sync-dist:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source repository
      - name: Checkout source repository
        uses: actions/checkout@v3

      # Sync dist to target repository
      - name: Sync dist to target repository
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          # Configure Git user
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Clone the target repository using the PAT
          git clone https://$PAT@github.com/ankudovychm/11ty-DSG-WEB.git target-repo
          cd target-repo

          # Ensure the target directory exists
          mkdir -p src/JsScripts/timeline/dist

          # Sync the dist folder into the specified location
          cp -R ../dist/* src/JsScripts/timeline/dist/

          # Commit and push changes
          git add src/JsScripts/timeline/dist
          git commit -m "Update dist folder in src/JsScripts/timeline/dist from dsg-gtimeline"
          git push origin main
